// <auto-generated />
using BloodDonation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloodDonation.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20210428182306_datainsert")]
    partial class datainsert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BloodDonation.Models.BloodDonor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BGroup");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Bihari Colony",
                            Age = 18,
                            BloodGroup = 2,
                            Email = "PiyushKumar@gmail.com",
                            FirstName = "Piyush",
                            Gender = 0,
                            LastName = "Kumar"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Kaushambi",
                            Age = 18,
                            BloodGroup = 0,
                            Email = "HarshKumar@gmail.com",
                            FirstName = "Harsh",
                            Gender = 0,
                            LastName = "Kumar"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Bhola Nath Nagar",
                            Age = 18,
                            BloodGroup = 1,
                            Email = "AdityaArora@gmail.com",
                            FirstName = "Aditya",
                            Gender = 0,
                            LastName = "Arora"
                        },
                        new
                        {
                            ID = 4,
                            Address = "GokulPuri",
                            Age = 18,
                            BloodGroup = 4,
                            Email = "HimanshuYadav@gmail.com",
                            FirstName = "Himanshu",
                            Gender = 0,
                            LastName = "Yadav"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
